service: aws-prune
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  # iam:
  #   role:
  #     statements:
  #       - Effect: Allow
  #         Action: 'ec2:*'
  #         Resource: '*'

functions:
  stop:
    handler: handler.stop
    events:
      - httpApi:
          path: /stop
          method: get